# Generated by Django 6.0.3 on 2026-04-05 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role_and_drop_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=50)),
                ('store_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('shop', 'Shop')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maplayout')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['user_id'], name='api_store_user_id_7bbdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['map_layout_id'], name='api_store_map_lay_973347_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('map_layout', 'node_id')},
        ),
    ]
