# Generated by Django 6.0.3 on 2026-04-05 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shop_shopcredential_warehouse_warehousecredential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('json_file', models.FileField(help_text='JSON file defining warehouses and shops', upload_to='network_definitions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
