# Generated by Django 6.0.3 on 2026-04-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_networkdefinition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customercredential",
            name="store",
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="store",
            name="api_store_user_id_7bbdb6_idx",
        ),
        migrations.RemoveIndex(
            model_name="store",
            name="api_store_map_lay_973347_idx",
        ),
        migrations.RemoveIndex(
            model_name="shop",
            name="api_shop_map_lay_deed31_idx",
        ),
        migrations.RemoveIndex(
            model_name="warehouse",
            name="api_warehou_map_lay_c81ac9_idx",
        ),
        migrations.AddField(
            model_name="networkdefinition",
            name="shared_password",
            field=models.CharField(
                default="DefaultPassword123!",
                help_text="Shared password for all users in this network",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="network_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.networkdefinition",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="network_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.networkdefinition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shop",
            unique_together={("network_definition", "node_id")},
        ),
        migrations.AlterUniqueTogether(
            name="warehouse",
            unique_together={("network_definition", "node_id")},
        ),
        migrations.AlterField(
            model_name="shopcredential",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehousecredential",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="shop",
            index=models.Index(
                fields=["network_definition_id"], name="api_shop_network_b434f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["network_definition_id"], name="api_warehou_network_6fc117_idx"
            ),
        ),
        migrations.DeleteModel(
            name="CustomerCredential",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="map_layout",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="map_layout",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
        migrations.DeleteModel(
            name="MapLayout",
        ),
    ]
