# Generated by Django 6.0.3 on 2026-04-05 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customercredential_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='demand_rate',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='target',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_node_id', models.CharField(max_length=50)),
                ('target_node_id', models.CharField(max_length=50)),
                ('travel_time', models.PositiveIntegerField(default=1)),
                ('transport_cost', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.networkdefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['network_definition_id'], name='api_route_network_848902_idx'), models.Index(fields=['source_node_id', 'target_node_id'], name='api_route_source__8f24ed_idx'), models.Index(fields=['is_active'], name='api_route_is_acti_04fd8a_idx')],
                'unique_together': {('network_definition', 'source_node_id', 'target_node_id')},
            },
        ),
    ]
